const animalData = [
    { word: "AARDVARK", definition: "A burrowing African mammal that feeds on ants and termites." },
    { word: "BABOON", definition: "A large monkey with a dog-like face found in Africa and Asia." },
    { word: "BEAVER", definition: "A large aquatic rodent known for building dams." },
    { word: "CHAMELEON", definition: "A lizard that can change color to match its surroundings." },
    { word: "COUGAR", definition: "A large, brown American wild cat, also known as a puma or mountain lion." },
    { word: "DOLPHIN", definition: "An intelligent marine mammal known for its playful behavior." },
    { word: "EAGLE", definition: "A large bird of prey with keen eyesight." },
    { word: "FERRET", definition: "A domesticated, slender animal related to the weasel." },
    { word: "GIRAFFE", definition: "A tall African mammal with a very long neck." },
    { word: "GOPHER", definition: "A burrowing rodent with large cheek pouches." },
    { word: "IGUANA", definition: "A large lizard often kept as a pet." },
    { word: "JAGUAR", definition: "A large, spotted cat found in Central and South America." },
    { word: "KANGAROO", definition: "An Australian marsupial that hops on its hind legs." },
    { word: "LEOPARD", definition: "A large, spotted wild cat, smaller than a jaguar." },
    { word: "MOLE", definition: "A small mammal that digs tunnels and lives underground." },
    { word: "NARWHAL", definition: "A small Arctic whale, with the male having a long, straight tusk." },
    { word: "PLATYPUS", definition: "An Australian egg-laying mammal with a duck-like bill." },
    { word: "QUOKKA", definition: "A small, friendly Australian marsupial often called the happiest animal." },
    { word: "RAVEN", definition: "A large, black bird known for its intelligence." },
    { word: "RHINO", definition: "A massive animal with one or two horns on its snout." },
    { word: "SLOTH", definition: "A slow-moving, tree-dwelling mammal from Central/South America." },
    { word: "TOUCAN", definition: "A tropical bird with a very large, colorful beak." },
    { word: "WALRUS", definition: "A large marine mammal with long tusks and flippers." },
    { word: "WOMBAT", definition: "A sturdy, burrowing Australian marsupial." },
    { word: "ZEBRA", definition: "An African wild horse with black-and-white stripes." }
];